[package]
name = "zwcamo"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
description = "Hide data inside strings using zero-width characters"
license = "Apache-2.0"

[dependencies]
zwc-encode = { path = ".." }
structopt = "0.3"
